# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigWindow(object):
    def setupUi(self, ConfigWindow):
        ConfigWindow.setObjectName("ConfigWindow")
        ConfigWindow.resize(279, 228)
        self.centralwidget = QtWidgets.QWidget(ConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cluster_method_box = QtWidgets.QComboBox(self.centralwidget)
        self.cluster_method_box.setObjectName("cluster_method_box")
        self.cluster_method_box.addItem("")
        self.cluster_method_box.addItem("")
        self.cluster_method_box.addItem("")
        self.cluster_method_box.addItem("")
        self.gridLayout.addWidget(self.cluster_method_box, 2, 1, 1, 1)
        self.risk_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.risk_label.sizePolicy().hasHeightForWidth())
        self.risk_label.setSizePolicy(sizePolicy)
        self.risk_label.setObjectName("risk_label")
        self.gridLayout.addWidget(self.risk_label, 1, 0, 1, 1)
        self.confirm_buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.confirm_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirm_buttonBox.setObjectName("confirm_buttonBox")
        self.gridLayout.addWidget(self.confirm_buttonBox, 5, 0, 1, 2)
        self.cluster_method_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_method_label.sizePolicy().hasHeightForWidth())
        self.cluster_method_label.setSizePolicy(sizePolicy)
        self.cluster_method_label.setObjectName("cluster_method_label")
        self.gridLayout.addWidget(self.cluster_method_label, 2, 0, 1, 1)
        self.weight_method_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_method_label.sizePolicy().hasHeightForWidth())
        self.weight_method_label.setSizePolicy(sizePolicy)
        self.weight_method_label.setObjectName("weight_method_label")
        self.gridLayout.addWidget(self.weight_method_label, 4, 0, 1, 1)
        self.weight_method_box = QtWidgets.QComboBox(self.centralwidget)
        self.weight_method_box.setObjectName("weight_method_box")
        self.weight_method_box.addItem("")
        self.weight_method_box.addItem("")
        self.gridLayout.addWidget(self.weight_method_box, 4, 1, 1, 1)
        self.order_method_box = QtWidgets.QComboBox(self.centralwidget)
        self.order_method_box.setObjectName("order_method_box")
        self.order_method_box.addItem("")
        self.order_method_box.addItem("")
        self.gridLayout.addWidget(self.order_method_box, 3, 1, 1, 1)
        self.risk_text = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.risk_text.sizePolicy().hasHeightForWidth())
        self.risk_text.setSizePolicy(sizePolicy)
        self.risk_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.risk_text.setObjectName("risk_text")
        self.gridLayout.addWidget(self.risk_text, 1, 1, 1, 1)
        self.order_method_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.order_method_label.sizePolicy().hasHeightForWidth())
        self.order_method_label.setSizePolicy(sizePolicy)
        self.order_method_label.setObjectName("order_method_label")
        self.gridLayout.addWidget(self.order_method_label, 3, 0, 1, 1)
        self.model_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_label.sizePolicy().hasHeightForWidth())
        self.model_label.setSizePolicy(sizePolicy)
        self.model_label.setObjectName("model_label")
        self.gridLayout.addWidget(self.model_label, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        ConfigWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigWindow)

    def retranslateUi(self, ConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfigWindow.setWindowTitle(_translate("ConfigWindow", "MainWindow"))
        self.cluster_method_box.setItemText(0, _translate("ConfigWindow", "single"))
        self.cluster_method_box.setItemText(1, _translate("ConfigWindow", "complete"))
        self.cluster_method_box.setItemText(2, _translate("ConfigWindow", "average"))
        self.cluster_method_box.setItemText(3, _translate("ConfigWindow", "ward"))
        self.risk_label.setText(_translate("ConfigWindow", "Risk(%):"))
        self.cluster_method_label.setText(_translate("ConfigWindow", "Cluster Method:"))
        self.weight_method_label.setText(_translate("ConfigWindow", "Weight Method:"))
        self.weight_method_box.setItemText(0, _translate("ConfigWindow", "var"))
        self.weight_method_box.setItemText(1, _translate("ConfigWindow", "equal"))
        self.order_method_box.setItemText(0, _translate("ConfigWindow", "top-down"))
        self.order_method_box.setItemText(1, _translate("ConfigWindow", "bisection"))
        self.risk_text.setPlaceholderText(_translate("ConfigWindow", "0"))
        self.order_method_label.setText(_translate("ConfigWindow", "Order Method:"))
        self.model_label.setText(_translate("ConfigWindow", "HRP model"))
